/**
 * @file
 * @exports
 * @summary This file contains the possible choices for the country an event is in
 */
module.exports = [
    'United States',
    'Andorra',
    'U.A.E',
    'Afghanistan',
    'Antigua',
    'Anguilla',
    'Albania',
    'Armenia',
    'Netherlands Antilles',
    'Angola',
    'Argentina',
    'American Samoa',
    'Austria',
    'Australia',
    'Aruba',
    'Aland Islands',
    'Azerbaijan',
    'Bosnia',
    'Barbados',
    'Bangladesh',
    'Belgium',
    'Burkina Faso',
    'Bulgaria',
    'Bahrain',
    'Burundi',
    'Benin',
    'Bermuda',
    'Brunei',
    'Bolivia',
    'Brazil',
    'Bahamas',
    'Bhutan',
    'Bouvet Island',
    'Botswana',
    'Belarus',
    'Belize',
    'Canada',
    'Cocos Islands',
    'Congo',
    'Central African Republic',
    'Congo Brazzaville',
    'Switzerland',
    'Cote Divoire',
    'Cook Islands',
    'Chile',
    'Cameroon',
    'China',
    'Colombia',
    'Costa Rica',
    'Serbia',
    'Cuba',
    'Cape Verde',
    'Christmas Island',
    'Cyprus',
    'Czech Republic',
    'Germany',
    'Djibouti',
    'Denmark',
    'Dominica',
    'Dominican Republic',
    'Algeria',
    'Ecuador',
    'Estonia',
    'Egypt',
    'Western Sahara',
    'Eritrea',
    'Spain',
    'Ethiopia',
    'European Union',
    'Finland',
    'Fiji',
    'Falkland Islands',
    'Micronesia',
    'Faroe Islands',
    'France',
    'Gabon',
    'United Kingdom',
    'England',
    'Scotland',
    'Wales',
    'Grenada',
    'Georgia',
    'French Guiana',
    'Ghana',
    'Gibraltar',
    'Greenland',
    'Gambia',
    'Guinea',
    'Guadeloupe',
    'Equatorial Guinea',
    'Greece',
    'Sandwich Islands',
    'Guatemala',
    'Guam',
    'Guinea - bissau',
    'Guyana',
    'Hong Kong',
    'Heard Island',
    'Honduras',
    'Croatia',
    'Haiti',
    'Hungary',
    'Indonesia',
    'Ireland',
    'Israel',
    'India',
    'Indian Ocean Territory',
    'Iraq',
    'Iran',
    'Iceland',
    'Italy',
    'Jamaica',
    'Jordan',
    'Japan',
    'Kenya',
    'Kyrgyzstan',
    'Cambodia',
    'Kiribati',
    'Comoros',
    'Saint Kitts And Nevis',
    'North Korea',
    'South Korea',
    'Kuwait',
    'Cayman Islands',
    'Kazakhstan',
    'Laos',
    'Lebanon',
    'Saint Lucia',
    'Liechtenstein',
    'Sri Lanka',
    'Liberia',
    'Lesotho',
    'Lithuania',
    'Luxembourg',
    'Latvia',
    'Libya',
    'Morocco',
    'Monaco',
    'Moldova',
    'Montenegro',
    'Madagascar',
    'Marshall Islands',
    'Macedonia',
    'Mali',
    'Burma',
    'Mongolia',
    'Macau',
    'Northern Mariana Islands',
    'Martinique',
    'Mauritania',
    'Montserrat',
    'Malta',
    'Mauritius',
    'Maldives',
    'Malawi',
    'Mexico',
    'Malaysia',
    'Mozambique',
    'Namibia',
    'New Caledonia',
    'Niger',
    'Norfolk Island',
    'Nigeria',
    'Nicaragua',
    'Netherlands',
    'Norway',
    'Nepal',
    'Nauru',
    'Niue',
    'New Zealand',
    'Oman',
    'Panama',
    'Peru',
    'French Polynesia',
    'New Guinea',
    'Philippines',
    'Pakistan',
    'Poland',
    'Saint Pierre',
    'Pitcairn Islands',
    'Puerto Rico',
    'Palestine',
    'Portugal',
    'Palau',
    'Paraguay',
    'Qatar',
    'Reunion',
    'Romania',
    'Serbia',
    'Russia',
    'Rwanda',
    'Saudi Arabia',
    'Solomon Islands',
    'Seychelles',
    'Sudan',
    'Sweden',
    'Singapore',
    'Saint Helena',
    'Slovenia',
    'Jan Mayen',
    'Slovakia',
    'Sierra Leone',
    'San Marino',
    'Senegal',
    'Somalia',
    'Suriname',
    'Sao Tome',
    'El Salvador',
    'Syria',
    'Swaziland',
    'Caicos Islands',
    'Chad',
    'French Territories',
    'Togo',
    'Thailand',
    'Tajikistan',
    'Tokelau',
    'Timorleste',
    'Turkmenistan',
    'Tunisia',
    'Tonga',
    'Turkey',
    'Trinidad',
    'Tuvalu',
    'Taiwan',
    'Tanzania',
    'Ukraine',
    'Uganda',
    'Us Minor Islands',
    'Uruguay',
    'Uzbekistan',
    'Vatican City',
    'Saint Vincent',
    'Venezuela',
    'British Virgin Islands',
    'Us Virgin Islands',
    'Vietnam',
    'Vanuatu',
    'Wallis And Futuna',
    'Samoa',
    'Yemen',
    'Mayotte',
    'South Africa',
    'Zambia',
    'Zimbabwe',
];
