module.exports = {
    'College of Arts and Sciences': {
        icon: 'flask',
        list: [
            'Ancient Studies',
            'Anthropology',
            'Art History',
            'Biochemistry',
            'Biology',
            'Chemistry',
            'Classical Studies',
            'Communication',
            'Computer Science',
            'Economics',
            'Engineering Physics',
            'English',
            'Environmental Science',
            'Environmental Studies',
            'Ethnic Studies',
            'Greek Language and Literature',
            'History',
            'Individual Studies',
            'Latin and Greek',
            'Latin Language and Literature',
            'Liberal Studies',
            'Mathematics',
            'Military Science',
            'Arabic',
            'Chinese',
            'French',
            'German',
            'Italian',
            'Japanese',
            'Spanish',
            'Music',
            'Neuroscience',
            'Philosophy',
            'Physics',
            'Political Science',
            'Psychology',
            'Public Health Science',
            'Religious Studies',
            'Sociology',
            'Theatre and Dance',
            'Women\'s and Gender Studies',
        ],
    },
    'School of Engineering': {
        icon: 'cogs',
        list: [
            'Bioengineering',
            'Civil Engineering',
            'Computer Science and Engineering',
            'Electrical Engineering',
            'General Engineering',
            'Mechanical Engineering',
            'Web Design and Engineering',
        ],
    },
    'Leavey School of Business': {
        icon: 'handshake outline',
        list: [
            'Accounting',
            'Accounting & Information Systems',
            'Economics',
            'Finance',
            'Individual Studies',
            'Management & Entrepreneurship',
            'Management Information Systems',
            'Marketing',
        ],
    },
};
